### ISSUE TITLE
Lab report 1 feedback

### ISSUE THREAD

**Issue by daniel-n-ryu** [brycepollack/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
  - URL not functional as markdown link
- [x] All relevant code examples written with backticks (```)
  - Correct markdown convention among programmers is to write commands using backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - Needs keystrokes
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Good work! Good to go as soon as the markdown link is fixed and keystroke count is added

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by brycepollack** [comment]
Hi,

Could you clarify on the two issues you marked? 

For the first one, "URL not functional as markdown link", should I submit the link to my lab report as https://brycepollack.github.io/cse15l-lab-reports/lab-report-1-week-2.md

Thanks,
Bryce

**Comment by daniel-n-ryu** [comment]
No, what you submitted was correct. I should have specified that the link you provided for downloading VScode does not function as a markdown link (i.e. you cannot click on the link and open the vscode download page)

**Comment by daniel-n-ryu** [comment]
well done
